apiVersion: v1
kind: Service
metadata:
  name: filemanager-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: filemanaguer
  ports:
  - port: 42500
    targetPort: 42500
    nodePort: 31010
  externalTrafficPolicy: Cluster
