apiVersion: v1
kind: Service
metadata:
  name:  mariadbapache
  namespace: default
spec:
  type: NodePort
  selector:
    app: mariadbapache
  ports:
  - port: 80
    targetPort:  80
    nodePort: 80
    name: apache
  - port: 3306  
    targetPort:  3306  
    nodePort: 3306
    name: mariadb
  externalTrafficPolicy:  Cluster
