apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kubernetes-servermultmatix
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servermultmatix
  template:
    metadata:
      labels:
        app: servermultmatix
    spec:
      containers:
      - name: kubernetes-servermultmatix
        image: docker.io/herex/servermultmatrix:1.0
