apiVersion: v1
kind: Service
metadata:
  name:  servermultmatrix-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: servermultmatrix
  ports:
  - port: 65000
    targetPort:  65000
    nodePort: 31000
  externalTrafficPolicy:  Cluster
