apiVersion: v1
kind: Service
metadata:
  name:  servermultmatrix-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: servermultmatix
  ports:
  - port: 41500
    targetPort:  41500
    nodePort: 31000
  externalTrafficPolicy:  Cluster
